data:
    name: 'HPatches'
    class_name: 'HPatches'
    batch_size: 1
    alteration: '' # choose when running engine on Hpatches evaluation, v for viewpoint, i for illumination, all for both
    resize_side: "short"
    resize: 480
    dist_thresh: 3.0
model:
    script: 'PointNeRF'
    class_name: 'Pointnerf'
    backbone:
      channels: [1, 64, 64, 128, 128]
      normalization: 'BatchNorm2d'
      activation: 'ReLU'
    detector_head:
      channels: [128, 128, 1]
      normalization: 'BatchNorm2d'
      activation: 'ReLU'
    descriptor_head:
      channels: [128, 128, 128]
      normalization: 'BatchNorm2d'
      activation: 'ReLU'
    scale_factor: 1.41
    bias: 9.0
matcher:
  method: "mnn"
  top_k: 10000
  dist_thresh: null
  max_ratio: null
  temperature: 0.1
  cross_check: True
pretrained: 'pointnerf_v1/pointnerf_v1_100000.pth'