data:
    gt_pairs: 'ScanNet/scannet_test_pairs_with_gt.txt'
    images_path:  'ScanNet'
    resize: [640,480]
    epi_thrsehold: 0.0005
    resize_float: false
model:
    model:
    script: 'PointNeRF'
    class_name: 'Pointnerf'
    backbone:
      channels: [1, 64, 64, 128, 128]
      normalization: 'BatchNorm2d'
      activation: 'ReLU'
    detector_head:
      channels: [128, 128, 1]
      normalization: 'BatchNorm2d'
      activation: 'ReLU'
    descriptor_head:
      channels: [128, 128, 128]
      normalization: 'BatchNorm2d'
      activation: 'ReLU'
    scale_factor: 1.41
matcher:
  method: "double_softmax"
  top_k: 10000
  dist_thresh: 0.6
  max_ratio: null
  temperature: 0.1
  cross_check: True
pretrained: 'pointnerf_pose_v1/pointnerf_pose_v1_5000.pth'